#include "Scene.h"
#include "Random.h"
#include "Time.h"
#include "Input.h"
#include "Platform.h"
//#include "SAM/SamLib.h"
#include "Debug.hpp"
#include "../../Game.h"
#include "Coroutiner.h"
#include "FileManager.hpp"
using CTRScissorMode = Enums::CTRScissorMode;